services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./assets:/app/assets
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
      - DOCKER_ENV=true

  sentiment-analysis:
    build:
      context: ./jobs/sentiment
      dockerfile: Dockerfile
    env_file:
      - ./jobs/sentiment/.env
    volumes:
      - ./logs:/app/logs 
      - ./cache:/app/cache 
    networks:
      - app-network
    runtime: nvidia
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_BIND_IP}:${MONGO_PORT}:${MONGO_PORT}"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./lib/mongodb:/data/db
    networks:
      - app-network
    stop_grace_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: